// pdfjs-dist v6+ ships ESM-only, so it's loaded via a dynamic import from this
// CommonJS module - a well-supported Node interop pattern, not a workaround.
// (An earlier attempt used the `pdf-parse` package, which turned out to bundle a
// long-abandoned 2016-era pdf.js internally that threw "bad XRef entry" on
// perfectly valid PDFs, including ones generated by pdfkit itself - confirmed via a
// direct side-by-side test before switching. pdfjs-dist is the actively maintained
// original the browser's own PDF viewer uses, so it's the reliable choice here.)
const pdfjsPromise = import('pdfjs-dist/legacy/build/pdf.mjs');

// Gemini could read a PDF natively as multimodal input; llama-3.3-70b-versatile is
// text-only, so the PDF has to be turned into plain text server-side before it's
// sent to the model at all. Used by both Resume Analyzer and the Voice Interview's
// /start endpoint - the two places a resume PDF reaches this service.
const extractPdfText = async (buffer) => {
  const pdfjsLib = await pdfjsPromise;
  // verbosity: 0 - we only extract text, never render, so the standard-font-metrics
  // warning pdfjs otherwise logs on every call is just noise here.
  const doc = await pdfjsLib.getDocument({ data: new Uint8Array(buffer), verbosity: 0 }).promise;

  let text = '';
  for (let pageNum = 1; pageNum <= doc.numPages; pageNum += 1) {
    const page = await doc.getPage(pageNum);
    const content = await page.getTextContent();
    text += `${content.items.map((item) => item.str).join(' ')}\n`;
  }

  return text;
};

module.exports = { extractPdfText };
